# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '10.0'
target 'Feature1' do
  
  use_frameworks!
  pod  'Core', :path => '../../../BB2.0_POC/ModularFramework/Core/'
end
